#!/bin/sh

sudo pacman -S ttf-ibm-plex feh picom bspwm sxhkd neovim xorg-xinit doas yarn node xsel

mkdir -p $HOME/.config/bspwm
mkdir -p $HOME/.config/sxhkd
mkdir -p $HOME/.config/polybar
mkdir -p $HOME/.config/nvim	
mkdir -p $HOME/.config/kitty
mkdir -p $HOME/.config/background

mv /$HOME/Gentoo/bspwmrc /$HOME/.config/bspwm/
mv /$HOME/Gentoo/sxhkdrc /$HOME/.config/sxhkd/
mv /$HOME/Gentoo/init.vim /$HOME/.config/nvim/
mv /$HOME/Gentoo/*.jpg /$HOME/.config/background/
mv /$HOME/Gentoo/kitty.conf /$HOME/.config/kitty/
